### ISSUE TITLE
question regarding StokeEnv

### ISSUE THREAD

**Issue by anthony0727** [HuantWang/SUPERSONIC#4]
we're trying to use StokeEnv and we're looking at master branch

seems like overall architecture is
c++ side <--gRPC--> python side
I see some of c++ side implementation using stoke in docker image `nwussimage/supersonic_0.1`

and I thought this is the class to use
https://github.com/HuantWang/SUPERSONIC/blob/bea7090e8bc4a54ed52495dd910ef946c88bec67/SuperSonic/utils/environments/Stoke_env.py#L35

but it's halted at
https://github.com/HuantWang/SUPERSONIC/blob/bea7090e8bc4a54ed52495dd910ef946c88bec67/SuperSonic/utils/environments/Stoke_env.py#L131

and also, I can't understand how stoke side's search procedure is triggered from `stoke_rl` class

really appreciate your help
thanks

**Comment by HuantWang** [comment]
Thanks for your interest. Sorry for the late reply, GitHub does not always remind me about issues :(.

> it's halted at

We use the [lock](https://github.com/HuantWang/SUPERSONIC/blob/bea7090e8bc4a54ed52495dd910ef946c88bec67/SuperSonic/utils/environments/Stoke_env.py#L131) to ensure that [the Markov Decision Process (MDP) process](https://github.com/HuantWang/SUPERSONIC/blob/bea7090e8bc4a54ed52495dd910ef946c88bec67/SuperSonic/utils/environments/Stoke_env.py#L135) executed success in parallel and releases when [lock_s.release()](https://github.com/HuantWang/SUPERSONIC/blob/bea7090e8bc4a54ed52495dd910ef946c88bec67/SuperSonic/utils/environments/Stoke_env.py#L140C13-L140C29) is called.

> I can't understand how stoke side's search procedure

The process is as follows:
On the C++ side, STOKE takes an action, steps to the next state, and sends the state and reward feedback to SUPERSONIC.
The communication is facilitated through gRPC.
On the Python side, SUPERSONIC receives the state and reward, processes them, and then provides feedback in the form of an action to STOKE.

Hope it helps. Feel free to ask me any questions.

**Comment by anthony0727** [comment]
right, but does `stoke_rl` work? 
and how should I instantiate it to work?

I've tried to instantiate (env = stoke_rl({some args})) inside the docker and it doesn't rollout quite well,
because it's halted at lock forever, which I think c++ side is not triggered properly so it's waiting forever

appreciate if you could provide a code snippet that we can use stoke env

Thanks for the reply!

**Comment by HuantWang** [comment]
> appreciate if you could provide a code snippet that we can use stoke env

Could you please try with [this tutorial](https://github.com/HuantWang/SUPERSONIC/blob/master/AE.md#24-case-study-4-superoptimization)?

> because it's halted at lock forever

Please ensure that Stoke can be executed individually. Then, could you test whether gRPC is working?

**Comment by anthony0727** [comment]
the tutorial works!
and Stoke works too.

how can we test gRPC is working?

**Comment by HuantWang** [comment]
You may find useful information about gRPC [here](https://github.com/HuantWang/SUPERSONIC/blob/master/INSTALL.md#12-grpc). If the tutorial works and isn't locked, I believe the gRPC interface is working.

**Comment by anthony0727** [comment]
Thanks for the reply,

However still, we can't make use of `stoke_rl` by itself

following the code, it seems like we have to run `run_synch.py` and instantiate `stoke_rl`?
still `stoke_rl`'s stepping halts at `lock`

can you tell me how to use StokeEnv solely on itself? so we can test our own algorithms

**Comment by HuantWang** [comment]
I'm not sure I understand you correctly. Do you want to test your RL algorithm for Stoke using the StokeEnv?

To resolve the lock problem, you should ensure that Stoke has been deployed before you start your RL interface. Once you've confirmed that Stoke is deployed and gRPC is working (RL can send actions to Stoke and the agent can receive rewards), the lock issue should be resolved. You can also 'print' or use 'log' to record the execution history, which can help you identify the location of the problem.

If the issue persists, you can try setting your RL environment worker count to 0 (close parallel execution) and remove the locking process. 

Hope it helps : )
